export class AppError extends Error {
  readonly statusCode: number;
  readonly code: string;
  readonly details?: string;
  /** Merged into JSON error body (e.g. existingJobId on 409). */
  readonly meta?: Record<string, unknown>;

  constructor(
    code: string,
    message: string,
    statusCode = 400,
    details?: string,
    meta?: Record<string, unknown>
  ) {
    super(message);
    this.code = code;
    this.statusCode = statusCode;
    this.details = details;
    this.meta = meta;
    this.name = "AppError";
  }
}

export const codes = {
  INVALID_URL: "INVALID_URL",
  DEVICE_NOT_REGISTERED: "DEVICE_NOT_REGISTERED",
  DEVICE_BLOCKED: "DEVICE_BLOCKED",
  RATE_LIMITED: "RATE_LIMITED",
  INVITE_CODE_INVALID: "INVITE_CODE_INVALID",
  INVITE_CODE_EXPIRED: "INVITE_CODE_EXPIRED",
  ANALYZE_FAILED: "ANALYZE_FAILED",
  /** yt-dlp DRM-protected sources (e.g. Spotify tracks) — no bypass attempted. */
  DRM_PROTECTED: "DRM_PROTECTED",
  DOWNLOAD_FAILED: "DOWNLOAD_FAILED",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  CONFLICT: "CONFLICT",
  BAD_REQUEST: "BAD_REQUEST",
  UNSUPPORTED_QUALITY: "UNSUPPORTED_QUALITY",
  /** Threads / unsupported extractor URLs — Flutter maps to friendly copy. */
  LINKCLIP_ERR_THREADS_UNSUPPORTED: "LINKCLIP_ERR_THREADS_UNSUPPORTED",
  LINKCLIP_ERR_PLATFORM_UNSUPPORTED: "LINKCLIP_ERR_PLATFORM_UNSUPPORTED",
  /** Analyze could not obtain format metadata (e.g. yt-dlp format resolution failure). */
  LINKCLIP_ERR_ANALYZE_METADATA_UNAVAILABLE: "LINKCLIP_ERR_ANALYZE_METADATA_UNAVAILABLE",
  /** Facebook: yt-dlp "Cannot parse data" and HTML/JSON fallback found no playable CDN URLs. */
  FACEBOOK_EXTRACT_FAILED: "FACEBOOK_EXTRACT_FAILED",
  /** YouTube bot challenge / expired cookies — analyze metadata blocked. */
  YOUTUBE_AUTH_REQUIRED: "YOUTUBE_AUTH_REQUIRED",
  /** YouTube geo / region restriction on the download server. */
  YOUTUBE_GEO_RESTRICTED: "YOUTUBE_GEO_RESTRICTED",
  /** yt-dlp found no downloadable formats (non-Facebook). */
  NO_DOWNLOADABLE_FORMATS: "NO_DOWNLOADABLE_FORMATS",
  /** Facebook extractor returned no video/audio formats. */
  FACEBOOK_NO_FORMATS_FOUND: "FACEBOOK_NO_FORMATS_FOUND",
  EDIT_JOB_NOT_FOUND: "EDIT_JOB_NOT_FOUND",
  EDIT_INVALID_SOURCE: "EDIT_INVALID_SOURCE",
  EDIT_FAILED: "EDIT_FAILED",
  EDIT_SOURCE_REQUIRED: "EDIT_SOURCE_REQUIRED",
  EDIT_MULTIPLE_SOURCES: "EDIT_MULTIPLE_SOURCES",
  EDIT_UPLOAD_NOT_FOUND: "EDIT_UPLOAD_NOT_FOUND",
  EDIT_UPLOAD_NOT_READY: "EDIT_UPLOAD_NOT_READY",
  EDIT_SOURCE_FILE_MISSING: "EDIT_SOURCE_FILE_MISSING",
  EDIT_AUDIO_INVALID_SOURCE: "EDIT_AUDIO_INVALID_SOURCE",
  EDIT_AUDIO_INVALID_TRIM: "EDIT_AUDIO_INVALID_TRIM",
  EDIT_AUDIO_UNSUPPORTED_OPERATION: "EDIT_AUDIO_UNSUPPORTED_OPERATION",
  EDIT_AUDIO_EXPORT_FAILED: "EDIT_AUDIO_EXPORT_FAILED",
  UNSUPPORTED_SPEED_FACTOR: "UNSUPPORTED_SPEED_FACTOR",
  UNSUPPORTED_ROTATION: "UNSUPPORTED_ROTATION",
  UNSUPPORTED_FORMAT_MODE: "UNSUPPORTED_FORMAT_MODE",
  UNSUPPORTED_CAPTIONS_MODE: "UNSUPPORTED_CAPTIONS_MODE",
  UNSUPPORTED_CAPTIONS_LANGUAGE: "UNSUPPORTED_CAPTIONS_LANGUAGE",
  UNSUPPORTED_CAPTIONS_STYLE: "UNSUPPORTED_CAPTIONS_STYLE",
  UNSUPPORTED_CAPTIONS_POSITION: "UNSUPPORTED_CAPTIONS_POSITION",
  /** Optional caption fine-offset out of accepted range (`offsetX` / `offsetY`) — surfaced like position errors. */
  UNSUPPORTED_CAPTIONS_POSITION_OFFSET: "UNSUPPORTED_CAPTIONS_POSITION_OFFSET",
  UNSUPPORTED_CAPTIONS_FONT_SIZE: "UNSUPPORTED_CAPTIONS_FONT_SIZE",
  UNSUPPORTED_CAPTIONS_FONT_FAMILY: "UNSUPPORTED_CAPTIONS_FONT_FAMILY",
  UNSUPPORTED_CAPTIONS_COLOR: "UNSUPPORTED_CAPTIONS_COLOR",
  UNSUPPORTED_CAPTIONS_WORD_HIGHLIGHT: "UNSUPPORTED_CAPTIONS_WORD_HIGHLIGHT",
  UNSUPPORTED_CAPTIONS_BOX_SHAPE: "UNSUPPORTED_CAPTIONS_BOX_SHAPE",
  CAPTIONS_TRANSCRIPTION_UNAVAILABLE: "CAPTIONS_TRANSCRIPTION_UNAVAILABLE",
  CAPTIONS_GENERATION_FAILED: "CAPTIONS_GENERATION_FAILED",
  /** Draft transcription failed / server cannot produce caption cues (without blocking by duration). */
  CAPTIONS_DRAFT_UNAVAILABLE: "CAPTIONS_DRAFT_UNAVAILABLE",
  /** Client-provided captions segments rejected (shape / empties vs mode). */
  INVALID_CAPTION_SEGMENTS: "INVALID_CAPTION_SEGMENTS",
  UPLOAD_FILE_TOO_LARGE: "UPLOAD_FILE_TOO_LARGE",
  UPLOAD_VIDEO_TOO_LONG: "UPLOAD_VIDEO_TOO_LONG",
  UPLOAD_UNSUPPORTED_TYPE: "UPLOAD_UNSUPPORTED_TYPE",
  UPLOAD_INVALID_VIDEO: "UPLOAD_INVALID_VIDEO",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  UPLOAD_NOT_FOUND: "UPLOAD_NOT_FOUND",
} as const;
